### ISSUE TITLE
Impr. Sugg.: also seek for AKA entries

### ISSUE THREAD

**Issue by Christoph21x** [ChrisRichner/ARGUS-TV-GuideEnhancer#11]
Current Guide Enricher seeks for the title (only).
It would be good, if it also seeks for AKA entries ("also known as").

Ex.: Broadcasted series title in German TV: "Sanctuary - Wächter der Kreaturen"
Series name under TheTVDB is simply "Sanctuary"
But an AKA "Sanctuary - Wächter der Kreaturen" is registered.

Would be perfect, if a seek for this AKA would also return a "successful".

Greetz - Chris

**Comment by ChrisRichner** [comment]
Thank you for this suggestion. Turns out that the used middleware for querying thetvdb.com does not support the AliasNames field. So to enable this feature one must first add support for <AliasNames> in the [tvdblib](https://github.com/svn2github/tvdblib) before the MatchMethods can make use of it.

For now you have to set up this kind of tv show manually by using the id instead of the name.

**Comment by ChrisRichner** [comment]
I've implemented your suggestion. I've also made a [Pull Request](https://github.com/svn2github/tvdblib/pull/1).
