### ISSUE TITLE
Minor: Uninstall - 2 issues

### ISSUE THREAD

**Issue by Christoph21x** [ChrisRichner/ARGUS-TV-GuideEnhancer#21]
Dear Chris

While having the need to uninstall GE, I found two (minor; first one: more severe than second) issues in the uninstall procedure:

1. Uninstall from Control Panel / Programs doesn't work at all, IF you're not a user with administrative account. Starting the uninstall from control panel/programs as a "normal user" ends up with the error:
![zwischenablage01](https://cloud.githubusercontent.com/assets/1575363/7230597/a9cbdea0-e76f-11e4-866b-f6a2d9d2923e.jpg)
I wasn't asked to log into Admin account before (as usual) - this is simply a missing step.
(The uninstall could nevertheless be performed by using the installation msi file selecting "Remove")

2. The directory isn't cleaned up properly - many left-behinds. GE should try to clean up everything, including removal of the directory. My directory after uninstall: 
![zwischenablage02](https://cloud.githubusercontent.com/assets/1575363/7230646/1c910578-e770-11e4-88a0-8f6490ad372f.jpg)
Most critical is undoubtedly the leftover *.dll files

Greetz - Chris

**Comment by ChrisRichner** [comment]
1. I've installed the Version 2.3.3 and uninstalled it many times for testing purpose on my Windows 10 dev system. The setup requires elevated privileges and the UAC Dialog kicks in as expected. 
2. The uninstall leaves the log and config.bak files on the disk by purpose. I assume that the other dll files are from a pre Version 2.3.0 install which should have been uninstalled by the older setup. Obviously that didn't work.

I suggest to close this because the 2.3.x setup's work as intended, ok?

**Comment by Christoph21x** [comment]
I agree and close this issue.
As in the other post described, I had four active installs of GE in the Win software repo. So I assume, this is an exception on my system.
As we probably get in the next days a 2.3.3.1 or 2.3.4 correct new release, I test it with THIS :)

Thanks Chris & greetz - Chris, too
